#!/bin/bash
# Limine boot menu theming: term palette/background matching the
# OneDark accents used everywhere else in the session (Waybar, mako,
# fuzzel, hyprlock), the sobarch wallpaper as a boot background, and
# branded interface text.
#
# UNVERIFIED: authored from Limine's documented CONFIG.md directives,
# not confirmed against a real boot. This sandbox has no EFI/bootloader
# environment to test a limine.conf against, and archinstall's exact
# generated file (which Limine version/config-format it targets) isn't
# available here either. Test on real hardware/a VM before relying on
# it: if the boot menu fails to render or Limine refuses to boot,
# delete the block between the START/END markers below from
# /boot/EFI/BOOT/limine.conf (rescue-media/live-USB access, same
# recovery path scripts/snapshot-rollback.sh already documents) and
# file a fix rather than trusting this script blindly. `term_font_scale`
# in particular is a first guess at "nice-looking" and worth tuning
# against a real display before trusting it not to run entries off
# screen on a small one.
#
# Deliberately narrow: only additive directives Limine has no config
# from archinstall to conflict with (term colors, wallpaper, branding
# text). `timeout`/`default_entry` are left alone since archinstall's
# own _add_limine_bootloader() may already set them and duplicate keys'
# behavior isn't confirmed.

set -euo pipefail

LIMINE_CONF="/boot/EFI/BOOT/limine.conf"
# Same package payload path ly-theme-setup.sh reads its ASCII logo
# from: sobarch-skel installs both under /usr/share/sobarch/branding/,
# built earlier in this same chroot session (see install_runner.py's
# CHROOT_SETUP_SCRIPTS ordering), well before the target user's $HOME
# exists, so neither script can read from a skel-deployed path instead.
WALLPAPER_SRC="/usr/share/sobarch/branding/sobarch-wallpaper.png"
WALLPAPER_DEST="/boot/sobarch-wallpaper.png"
START_MARKER="#### SOBARCH THEME START (auto-generated by limine-theme-setup.sh, do not edit by hand)"
END_MARKER="#### SOBARCH THEME END"

cp -f "$WALLPAPER_SRC" "$WALLPAPER_DEST"

# wallpaper_style centered (not stretched): the wallpaper is a fixed
# 1920x1080 raster, and stretching it to an arbitrary boot resolution
# would distort the mark. backdrop matches the wallpaper's own
# background fill so the letterboxing around it (any resolution larger
# than 1920x1080) is seamless rather than a visible border.
block="$START_MARKER
interface_branding: Sobarch
interface_branding_color: 61afef
interface_help_color: 56b6c2
interface_help_color_bright: 61afef
term_font_scale: 2x2
wallpaper: boot():/sobarch-wallpaper.png
wallpaper_style: centered
backdrop: 282c34
term_background: 282c34
term_foreground: abb2bf
term_palette: 282c34;e06c75;98c379;e5c07b;61afef;c678dd;56b6c2;abb2bf
term_palette_bright: 545862;e06c75;98c379;e5c07b;61afef;c678dd;56b6c2;c8ccd4
$END_MARKER"

if grep -qF "$START_MARKER" "$LIMINE_CONF"; then
    awk -v start="$START_MARKER" -v end="$END_MARKER" -v block="$block" '
        $0 == start { print block; skipping = 1; next }
        $0 == end && skipping { skipping = 0; next }
        skipping { next }
        { print }
    ' "$LIMINE_CONF" > "${LIMINE_CONF}.sobarch-new"
    mv "${LIMINE_CONF}.sobarch-new" "$LIMINE_CONF"
else
    # Global directives must precede every /Title entry block, so this
    # goes at the top of the file, not appended like
    # rescue-iso-setup.sh's own entry block.
    printf '%s\n\n%s' "$block" "$(cat "$LIMINE_CONF")" > "${LIMINE_CONF}.sobarch-new"
    mv "${LIMINE_CONF}.sobarch-new" "$LIMINE_CONF"
fi

echo "limine-theme-setup.sh: done (unverified, check the boot menu on first reboot)."
