#!/bin/bash
# Limine boot menu theming: term palette/background matching the
# OneDark accents used everywhere else in the session (Waybar, mako,
# fuzzel, hyprlock), plus branded interface text.
#
# No wallpaper image: Limine's menu (title/help text/entry list) is
# drawn at a fixed, centered position with no way to reserve space
# around it, so any image large enough to read as a logo eventually
# clashes with that text at some resolution (confirmed on real
# hardware: a centered mark, then a corner-placed one, both still
# collided with the menu). Omarchy's own default limine.conf (checked
# directly, github.com/basecamp/omarchy) takes the same way out - a
# flat `backdrop` color plus the terminal palette, no `wallpaper`
# directive - so this script follows that precedent instead of
# continuing to fight the layout.
#
# Runs twice in this script's lifetime, unmodified either time: once
# raw-copied into the target and run inside arch-chroot at install time
# (install_runner.py's CHROOT_SETUP_SCRIPTS), and later, packaged as
# /usr/local/lib/sobarch/limine-theme-setup.sh by sobarch-scripts,
# re-run by update-config-menu.sh (via pkexec) whenever sobarch-skel
# refreshes so an already-installed system picks up branding changes
# too. Nothing here depends on being inside a fresh chroot specifically
# (no archinstall-only env vars), and the block-replace logic below is
# already idempotent, so no separate "refresh" variant was needed.
#
# Confirmed on real hardware (photos of an actual boot menu): the
# branding text, term_font_scale 2x2, and color palette below all
# render as intended. The one part that didn't - a wallpaper image
# behind the menu - is why this script no longer sets one; see above.
#
# Deliberately narrow: only additive directives Limine has no config
# from archinstall to conflict with (term colors, branding text).
# `timeout`/`default_entry` are left alone since archinstall's own
# _add_limine_bootloader() may already set them and duplicate keys'
# behavior isn't confirmed.

set -euo pipefail

LIMINE_CONF="/boot/EFI/BOOT/limine.conf"

# Leftover from when this script used to copy a wallpaper here; a
# machine that already ran that version has this file sitting on its
# ESP with nothing referencing it anymore.
rm -f /boot/sobarch-wallpaper.png

START_MARKER="#### SOBARCH THEME START (auto-generated by limine-theme-setup.sh, do not edit by hand)"
END_MARKER="#### SOBARCH THEME END"

block="$START_MARKER
interface_branding: Sobarch
interface_branding_color: 61afef
interface_help_color: 56b6c2
interface_help_color_bright: 61afef
term_font_scale: 2x2
backdrop: 282c34
term_background: 282c34
term_foreground: abb2bf
term_palette: 282c34;e06c75;98c379;e5c07b;61afef;c678dd;56b6c2;abb2bf
term_palette_bright: 545862;e06c75;98c379;e5c07b;61afef;c678dd;56b6c2;c8ccd4
$END_MARKER"

if grep -qF "$START_MARKER" "$LIMINE_CONF"; then
    awk -v start="$START_MARKER" -v end="$END_MARKER" -v block="$block" '
        $0 == start { print block; skipping = 1; next }
        $0 == end && skipping { skipping = 0; next }
        skipping { next }
        { print }
    ' "$LIMINE_CONF" > "${LIMINE_CONF}.sobarch-new"
    mv "${LIMINE_CONF}.sobarch-new" "$LIMINE_CONF"
else
    # Global directives must precede every /Title entry block, so this
    # goes at the top of the file, not appended like
    # rescue-iso-setup.sh's own entry block.
    printf '%s\n\n%s' "$block" "$(cat "$LIMINE_CONF")" > "${LIMINE_CONF}.sobarch-new"
    mv "${LIMINE_CONF}.sobarch-new" "$LIMINE_CONF"
fi

echo "limine-theme-setup.sh: done."
