#!/bin/bash
# Limine boot menu theming: term palette/background matching the
# OneDark accents used everywhere else in the session (Waybar, mako,
# fuzzel, hyprlock), a small centered logo mark, and branded interface
# text.
#
# Earlier version of this script dropped the logo entirely because it
# clashed with the menu text at some resolutions. Two actual bugs
# caused that, both fixed here instead of giving up on a logo:
#   - It used the full opaque 1920x1080 desktop wallpaper as the boot
#     background. Now uses sobarch-logo.png instead, the same small,
#     mostly-transparent mark hyprlock uses - centered at its native
#     512x512 size (`wallpaper_style: centered`) it only occupies a
#     modest chunk of screen space.
#   - `term_background` was set to a bare 6-digit RRGGBB value, but per
#     Limine's CONFIG.md that field is `TTRRGGBB` (leading transparency
#     byte). A malformed value there meant the menu's text background
#     never got the transparency needed to let the logo show through.
#     Now set as `80282c34`: alpha 0x80, matching the semi-transparent
#     alpha Limine itself defaults to whenever a `wallpaper` is set.
#   - `term_font_scale` was forced to `2x2` (double size), inflating
#     the menu's on-screen footprint well beyond what it needs. Left
#     unset now so it falls back to Limine's own resolution-based
#     default (1x1 below 2560x1440, 2x2 above).
#
# Runs twice in this script's lifetime, unmodified either time: once
# raw-copied into the target and run inside arch-chroot at install time
# (install_runner.py's CHROOT_SETUP_SCRIPTS), and later, packaged as
# /usr/local/lib/sobarch/limine-theme-setup.sh by sobarch-scripts,
# re-run by update-config-menu.sh (via pkexec) whenever sobarch-skel
# refreshes so an already-installed system picks up branding changes
# too. Nothing here depends on being inside a fresh chroot specifically
# (no archinstall-only env vars), and the block-replace logic below is
# already idempotent, so no separate "refresh" variant was needed.
#
# UNVERIFIED on real hardware since the changes above: the branding
# text and color palette were confirmed working before, but the
# reinstated wallpaper/transparency/font-scale changes have not been
# checked against an actual boot yet. If the logo still collides with
# the menu or is still hidden, delete the block between the
# START/END markers below from /boot/EFI/BOOT/limine.conf
# (rescue-media/live-USB access, same recovery path
# scripts/snapshot-rollback.sh already documents) and file a fix rather
# than trusting this script blindly.
#
# Deliberately narrow: only additive directives Limine has no config
# from archinstall to conflict with (term colors, wallpaper, branding
# text). `timeout`/`default_entry` are left alone since archinstall's
# own _add_limine_bootloader() may already set them and duplicate keys'
# behavior isn't confirmed.

set -euo pipefail

LIMINE_CONF="/boot/EFI/BOOT/limine.conf"
# Same package payload path ly-theme-setup.sh reads its ASCII logo
# from: sobarch-skel installs both under /usr/share/sobarch/branding/,
# built earlier in this same chroot session (see install_runner.py's
# CHROOT_SETUP_SCRIPTS ordering), well before the target user's $HOME
# exists, so neither script can read from a skel-deployed path instead.
WALLPAPER_SRC="/usr/share/sobarch/branding/sobarch-logo.png"
WALLPAPER_DEST="/boot/sobarch-logo.png"

# Leftover from the full-wallpaper version of this script; a machine
# that already ran that version has this file sitting on its ESP with
# nothing referencing it anymore.
rm -f /boot/sobarch-wallpaper.png

cp -f "$WALLPAPER_SRC" "$WALLPAPER_DEST"

START_MARKER="#### SOBARCH THEME START (auto-generated by limine-theme-setup.sh, do not edit by hand)"
END_MARKER="#### SOBARCH THEME END"

block="$START_MARKER
interface_branding: Sobarch
interface_branding_color: 61afef
interface_help_color: 56b6c2
interface_help_color_bright: 61afef
wallpaper: boot():/sobarch-logo.png
wallpaper_style: centered
backdrop: 282c34
term_background: 80282c34
term_foreground: abb2bf
term_palette: 282c34;e06c75;98c379;e5c07b;61afef;c678dd;56b6c2;abb2bf
term_palette_bright: 545862;e06c75;98c379;e5c07b;61afef;c678dd;56b6c2;c8ccd4
$END_MARKER"

if grep -qF "$START_MARKER" "$LIMINE_CONF"; then
    awk -v start="$START_MARKER" -v end="$END_MARKER" -v block="$block" '
        $0 == start { print block; skipping = 1; next }
        $0 == end && skipping { skipping = 0; next }
        skipping { next }
        { print }
    ' "$LIMINE_CONF" > "${LIMINE_CONF}.sobarch-new"
    mv "${LIMINE_CONF}.sobarch-new" "$LIMINE_CONF"
else
    # Global directives must precede every /Title entry block, so this
    # goes at the top of the file, not appended like
    # rescue-iso-setup.sh's own entry block.
    printf '%s\n\n%s' "$block" "$(cat "$LIMINE_CONF")" > "${LIMINE_CONF}.sobarch-new"
    mv "${LIMINE_CONF}.sobarch-new" "$LIMINE_CONF"
fi

echo "limine-theme-setup.sh: done."
