#!/bin/bash
# ly greeter theming: ly 1.4.1+ (the Zig rewrite Arch's `ly` package
# actually ships, confirmed against archlinux.org/packages/extra/
# x86_64/ly) configures itself via /etc/ly/config.lua, not the
# config.ini this script used to write. That ini-based schema is gone
# in this version: the keys previously written here (animation=colormix,
# bigclock=en, min_refresh_delta, blank_password) don't exist in the
# packaged config.lua's own defaults at all and would have silently
# done nothing.
#
# The centerpiece is the sobarch mark rendered as ASCII art via ly's
# "lua" animation type (a LuaJIT script implementing draw(), see
# fairyglade/ly's Lua Animation API: ly.putLabel/ly.width/ly.height),
# sourced from the same branding/sobarch-logo-ascii.txt fastfetch
# already uses. Read here from the sobarch-skel package payload
# (/usr/share/sobarch/branding/, already installed onto the target
# earlier in this same chroot session; see limine-theme-setup.sh's own
# comment for why there's no $HOME yet to read a skel-deployed copy from).
#
# UNVERIFIED: no display/TTY in this sandbox to confirm the greeter
# actually renders this. Low-risk to get wrong regardless: a Lua
# runtime error just shows ly's own solid-red error screen instead of
# the greeter failing to start, and a bad config.lua value degrades
# the login screen's look, not the machine's ability to boot to a TTY.
# Sanity-check by watching the first real login screen.

set -euo pipefail

LOGO_SRC="/usr/share/sobarch/branding/sobarch-logo-ascii.txt"
LOGO_LUA="/etc/ly/sobarch-logo.lua"

mkdir -p /etc/ly

# branding/sobarch-logo-ascii.txt lines are prefixed with a literal
# "$1", fastfetch's own placeholder syntax for its "file" logo type
# (see skel/.config/fastfetch/config.jsonc). ly has no equivalent
# substitution mechanism, so that prefix is just stripped here and the
# whole logo is drawn in one fixed accent color from Lua instead.
{
    echo "-- Auto-generated by ly-theme-setup.sh from sobarch's branding assets, do not edit by hand."
    echo "local logo = {"
    sed 's/^\$1//' "$LOGO_SRC" | while IFS= read -r line; do
        escaped=${line//\\/\\\\}
        escaped=${escaped//\"/\\\"}
        printf '    "%s",\n' "$escaped"
    done
    echo "}"
    cat <<'EOF'

-- Full color (SS byte 0x00), no styling flags.
local accent = 0x0061afef

function draw()
    local start_y = math.floor((ly.height - #logo) / 2)
    for i, line in ipairs(logo) do
        local x = math.floor((ly.width - #line) / 2)
        ly.putLabel(line, accent, 0x00000000, x, start_y + i - 1)
    end
end
EOF
} > "$LOGO_LUA"

cat > /etc/ly/config.lua <<EOF
ly = {
    allow_empty_password = false,
    animation = "lua",
    -- Static logo, not a real animation, so redrawing every 5ms
    -- (the ly default) would just burn CPU on an idle greeter.
    animation_frame_delay = 1000,
    lua_animation_file = "$LOGO_LUA",
    bigclock = "none",
    clock = "%a %d %b  %H:%M",
    bg = 0x00282c34,
    fg = 0x00abb2bf,
    border_fg = 0x0061afef,
    hide_borders = false,
}
EOF

echo "ly-theme-setup.sh: done (unverified, check the greeter on first reboot)."
