#!/bin/bash
# ly greeter theming: ly 1.4.1+ (the Zig rewrite Arch's `ly` package
# actually ships, confirmed against archlinux.org/packages/extra/
# x86_64/ly) configures itself via /etc/ly/config.lua, not the
# config.ini this script used to write. That ini-based schema is gone
# in this version: the keys previously written here (animation=colormix,
# bigclock=en, min_refresh_delta, blank_password) don't exist in the
# packaged config.lua's own defaults at all and would have silently
# done nothing.
#
# Runs twice in this script's lifetime, unmodified either time: once
# raw-copied into the target and run inside arch-chroot at install time
# (install_runner.py's CHROOT_SETUP_SCRIPTS), and later, packaged as
# /usr/local/lib/sobarch/ly-theme-setup.sh by sobarch-scripts, re-run by
# update-config-menu.sh (via pkexec) whenever sobarch-skel refreshes so
# an already-installed system picks up branding changes too. Nothing
# here depends on being inside a fresh chroot specifically (no
# archinstall-only env vars), and every write below already overwrites
# unconditionally, so no separate "refresh" variant was needed. A
# config.lua/sobarch-logo.lua rewrite only takes effect the next time ly
# itself starts (reboot, or `systemctl restart ly`); this script doesn't
# force that.
#
# The centerpiece is the sobarch mark animated via ly's "lua" animation
# type: the glyph cells parsed out of branding/sobarch-logo-ascii.txt
# (the same source fastfetch uses) fly in from the screen edges,
# assemble into the mark, hold with a slow breathing glow, then fly
# apart and repeat. Read here from the sobarch-skel package payload
# (/usr/share/sobarch/branding/, already installed onto the target
# earlier in this same chroot session; see limine-theme-setup.sh's own
# comment for why there's no $HOME yet to read a skel-deployed copy from).
#
# The Lua API calls below (ly.clock/putCell/putLabel/width/height) are
# checked against fairyglade/ly's upstream source rather than guessed:
# src/animations/Lua.zig (clock() returns microseconds; putCell and
# putLabel both take (value, fg, bg, x, y); width/height are refreshed
# before every draw() call) and ly-ui/src/TerminalBuffer.zig (the
# screen is cleared to the configured bg before each frame, and
# 0x00000000 as a fg/bg value is TerminalBuffer.DEFAULT, meaning "use
# the configured color", not literal black). That's why the animation
# below never has to paint its own background: it only draws the cells
# it wants visible this frame and lets ly clear the rest.
#
# UNVERIFIED: no display/TTY in this sandbox to confirm the greeter
# actually renders this, even with the API usage checked against
# upstream source above. Low-risk to get wrong regardless: a Lua
# runtime error just shows ly's own solid-red error screen instead of
# the greeter failing to start, and a bad config.lua value degrades
# the login screen's look, not the machine's ability to boot to a TTY.
# Sanity-check by watching the first real login screen.

set -euo pipefail

LOGO_SRC="/usr/share/sobarch/branding/sobarch-logo-ascii.txt"
LOGO_LUA="/etc/ly/sobarch-logo.lua"

mkdir -p /etc/ly

# branding/sobarch-logo-ascii.txt lines are prefixed with a literal
# "$1", fastfetch's own placeholder syntax for its "file" logo type
# (see skel/.config/fastfetch/config.jsonc). ly has no equivalent
# substitution mechanism, so that prefix is just stripped here; the
# stripped bitmap becomes both the "#" cells the animation below flies
# into place and the text ly.putLabel draws once it's settled.
{
    echo "-- Auto-generated by ly-theme-setup.sh from sobarch's branding assets, do not edit by hand."
    echo "local logo = {"
    sed 's/^\$1//' "$LOGO_SRC" | while IFS= read -r line; do
        escaped=${line//\\/\\\\}
        escaped=${escaped//\"/\\\"}
        printf '    "%s",\n' "$escaped"
    done
    echo "}"
    cat <<'EOF'

local t = table
local bit = bit

-- OneDark accent, matching interface_branding_color in
-- limine-theme-setup.sh's Limine block and the same accent used across
-- Waybar/mako/fuzzel/hyprlock (see skel/.config/sobarch/tinty-templates).
local accent = 0x0061afef
-- OneDark "bright black": Limine's term_palette_bright base, reused
-- here as the color a particle fades in from and back out to.
local accent_dim = 0x00545862
-- ly-ui's TerminalBuffer.DEFAULT: lets ly's own per-frame clear (to
-- config.lua's bg) show through instead of painting literal black.
local transparent = 0x00000000

local WORDMARK = "sobarch"

-- Config
local CONVERGE_TIME = 2.2e6 -- microseconds: mark flying in and landing
local HOLD_TIME = 5.0e6     -- microseconds: mark holding still, breathing
local DISPERSE_TIME = 1.2e6 -- microseconds: mark flying back apart
-- Fraction of CONVERGE/DISPERSE spent staggering when each particle
-- starts moving, so the mark reads as assembling rather than sliding
-- in as one rigid block.
local STAGGER = 0.5
local CYCLE_TIME = CONVERGE_TIME + HOLD_TIME + DISPERSE_TIME
-- Config

-- One particle per "#" cell in the logo bitmap above. ly.width/height
-- track the terminal size and are refreshed before every draw() call,
-- so targets are recomputed from them each frame instead of cached
-- once, which would drift on a mid-animation resize.
local function targets()
    local list = {}
    local start_y = math.floor((ly.height - #logo) / 2)
    for row, line in ipairs(logo) do
        local start_x = math.floor((ly.width - #line) / 2)
        for col = 1, #line do
            if line:sub(col, col) == "#" then
                t.insert(list, { x = start_x + col - 1, y = start_y + row - 1 })
            end
        end
    end
    return list
end

-- Weighted onto the four screen edges so particles read as flying in
-- from off-frame rather than fading in in place.
local function spawn_point()
    local edge = math.random(1, 4)
    if edge == 1 then return math.random(0, ly.width - 1), 0
    elseif edge == 2 then return math.random(0, ly.width - 1), ly.height - 1
    elseif edge == 3 then return 0, math.random(0, ly.height - 1)
    else return ly.width - 1, math.random(0, ly.height - 1) end
end

local particles = {}
local function reroll_particles(count)
    for i = 1, count do
        local sx, sy = spawn_point()
        particles[i] = particles[i] or {}
        particles[i].sx, particles[i].sy = sx, sy
        particles[i].delay = math.random() * STAGGER
    end
end

local function ease_out_cubic(x)
    local u = 1 - x
    return 1 - u * u * u
end
local function ease_in_cubic(x)
    return x * x * x
end
local function lerp(a, b, x)
    return a + (b - a) * x
end
local function lerp_color(c1, c2, x)
    local r = math.floor(lerp(bit.band(bit.rshift(c1, 16), 0xff), bit.band(bit.rshift(c2, 16), 0xff), x))
    local g = math.floor(lerp(bit.band(bit.rshift(c1, 8), 0xff), bit.band(bit.rshift(c2, 8), 0xff), x))
    local b = math.floor(lerp(bit.band(c1, 0xff), bit.band(c2, 0xff), x))
    return bit.bor(b, bit.bor(bit.lshift(r, 16), bit.lshift(g, 8)))
end

local start_clock = ly.clock()
local last_cycle = -1

function draw()
    local list = targets()
    -- First frame only: particles starts empty, so this seeds it
    -- before the cycle-boundary reroll below ever runs.
    if #particles ~= #list then
        reroll_particles(#list)
    end

    local elapsed_total = ly.clock() - start_clock
    local cycle = math.floor(elapsed_total / CYCLE_TIME)
    if cycle ~= last_cycle then
        if last_cycle >= 0 then reroll_particles(#list) end
        last_cycle = cycle
    end
    local elapsed = elapsed_total - cycle * CYCLE_TIME

    -- putCell/putLabel coordinates go straight to ly-ui as unsigned
    -- ints; an out-of-range value raises a Lua error and blanks the
    -- screen to ly's red error page, so every draw is bounds-checked.
    if elapsed < CONVERGE_TIME then
        local phase_t = elapsed / CONVERGE_TIME
        for i, tgt in ipairs(list) do
            local p = particles[i]
            local pt = math.max(0, math.min(1, (phase_t - p.delay) / (1 - p.delay)))
            if pt > 0 then
                local e = ease_out_cubic(pt)
                local x = math.floor(lerp(p.sx, tgt.x, e) + 0.5)
                local y = math.floor(lerp(p.sy, tgt.y, e) + 0.5)
                if x >= 0 and x < ly.width and y >= 0 and y < ly.height then
                    ly.putCell(string.byte('#'), lerp_color(accent_dim, accent, e), transparent, x, y)
                end
            end
        end
    elseif elapsed < CONVERGE_TIME + HOLD_TIME then
        local hold_t = elapsed - CONVERGE_TIME
        local pulse = 0.5 + 0.5 * math.sin(hold_t / 700000)
        local col = lerp_color(accent, 0x00ffffff, pulse * 0.15)
        local start_y = math.floor((ly.height - #logo) / 2)
        for row, line in ipairs(logo) do
            local x = math.floor((ly.width - #line) / 2)
            local y = start_y + row - 1
            if x >= 0 and y >= 0 and y < ly.height then
                ly.putLabel(line, col, transparent, x, y)
            end
        end
        local wm_y = start_y + #logo + 1
        local wm_x = math.floor((ly.width - #WORDMARK) / 2)
        if wm_x >= 0 and wm_y >= 0 and wm_y < ly.height then
            ly.putLabel(WORDMARK, col, transparent, wm_x, wm_y)
        end
    else
        local phase_t = (elapsed - CONVERGE_TIME - HOLD_TIME) / DISPERSE_TIME
        for i, tgt in ipairs(list) do
            local p = particles[i]
            local pt = math.max(0, math.min(1, (phase_t - p.delay) / (1 - p.delay)))
            local e = ease_in_cubic(pt)
            local x = math.floor(lerp(tgt.x, p.sx, e) + 0.5)
            local y = math.floor(lerp(tgt.y, p.sy, e) + 0.5)
            if x >= 0 and x < ly.width and y >= 0 and y < ly.height then
                ly.putCell(string.byte('#'), lerp_color(accent, accent_dim, e), transparent, x, y)
            end
        end
    end
end
EOF
} > "$LOGO_LUA"

cat > /etc/ly/config.lua <<EOF
ly = {
    allow_empty_password = false,
    animation = "lua",
    -- Milliseconds between draw() calls (src/config/Config.zig's own
    -- default is 5). A moving animation needs this low enough to read
    -- as smooth; 40 is ~25fps, well under the default's redraw rate.
    animation_frame_delay = 40,
    lua_animation_file = "$LOGO_LUA",
    bigclock = "none",
    clock = "%a %d %b  %H:%M",
    bg = 0x00282c34,
    fg = 0x00abb2bf,
    border_fg = 0x0061afef,
    hide_borders = false,
}
EOF

echo "ly-theme-setup.sh: done (unverified, check the greeter on first reboot)."
