#!/bin/bash
# ly greeter theming: the actual installed `ly` package (confirmed
# 1.4.1-1 against a real test machine's `pacman -Qi ly`) configures
# itself via /etc/ly/config.ini, not config.lua. An earlier version of
# this script targeted config.lua, on the assumption that ly 1.4.1+
# had switched to a Lua-scripted config the way fairyglade/ly's GitHub
# master branch has (its src/animations/Lua.zig, confirmed against that
# upstream source). That assumption was wrong for this package build:
# `pacman -Ql ly` on the test machine shows only config.ini/
# config.ini.example, no config.lua or example.lua anywhere, and
# `ldd /usr/bin/ly-dm | grep -i lua` finds no Lua library linked in at
# all. Whatever version of ly eventually ships that feature, it isn't
# this one, so config.lua was silently doing nothing the entire time
# this script wrote it -- caught because a rebooted test machine kept
# showing ly's own stock colormix+bigclock look (the actual compiled-in
# defaults) instead of any sobarch branding at all.
#
# Runs twice in this script's lifetime, unmodified either time: once
# raw-copied into the target and run inside arch-chroot at install time
# (install_runner.py's CHROOT_SETUP_SCRIPTS), and later, packaged as
# /usr/local/lib/sobarch/ly-theme-setup.sh by sobarch-scripts, re-run by
# update-config-menu.sh (via pkexec) whenever sobarch-skel refreshes so
# an already-installed system picks up branding changes too. Nothing
# here depends on being inside a fresh chroot specifically (no
# archinstall-only env vars), and every write below already overwrites
# unconditionally, so no separate "refresh" variant was needed. A
# config.ini/sobarch-logo.dur rewrite only takes effect the next time ly
# itself starts (reboot, or `systemctl restart ly@tty1` -- the unit is
# templated per-tty, confirmed against the test machine's own
# `pacman -Ql ly`, not a plain `ly.service`); this script doesn't force
# that.
#
# The centerpiece is the sobarch mark played back via ly's built-in
# `dur_file` animation type (config.ini's `animation` key has a fixed
# enum: none/doom/matrix/colormix/gameoflife/dur_file -- confirmed
# against the test machine's own /etc/ly/config.ini.example -- there is
# no way to point it at a custom script). The .dur file itself
# (branding/sobarch-logo.dur) is a prebuilt gzip-compressed JSON asset,
# not generated here the way the old Lua table was: its schema was
# checked field-by-field against ly's own shipped res/example.dur and
# src/animations/DurFile.zig from fairyglade/ly's upstream source
# (formatVersion must be exactly 7; colorMap is indexed [x][y]; the
# (fg, bg) index pairs it uses are copied verbatim from pairs already
# proven to render in that reference file, not newly picked, since
# DurFile.zig's index-to-color remap is fiddly enough that a "new" pair
# would be a guess rather than a verification). If the mark in
# branding/sobarch-logo-ascii.txt ever changes, sobarch-logo.dur has to
# be regenerated by hand to match; see sobarch-skel's PKGBUILD comment
# on it.
#
# UNVERIFIED: no display/TTY in this sandbox to confirm the greeter
# actually renders this, even with the schema checked against upstream
# source and a real installed ly above. A malformed .dur file is lower
# risk to get wrong than the old Lua script was: DurFile.zig either
# accepts it or ly falls back to its own defaults (the same "stock
# colormix" look this whole investigation started from), not a crash.
# Sanity-check by watching the first real login screen.

set -euo pipefail

LOGO_SRC="/usr/share/sobarch/branding/sobarch-logo.dur"
LOGO_DUR="/etc/ly/sobarch-logo.dur"

mkdir -p /etc/ly

cp -f "$LOGO_SRC" "$LOGO_DUR"

# Leftovers from this script's earlier config.lua-based version: ly
# never reads them (confirmed above), but a stale config.lua sitting
# next to config.ini is a red herring for whoever debugs this next.
rm -f /etc/ly/config.lua /etc/ly/sobarch-logo.lua

# OneDark, same values used across Limine (limine-theme-setup.sh's own
# interface_branding_color/term_palette), Waybar, mako, fuzzel and
# hyprlock. config.ini's color fields use the same 0xSSRRGGBB truecolor
# format config.lua did (confirmed identical against the test machine's
# own config.ini.example header comment), so these carry over unchanged.
cat > /etc/ly/config.ini <<EOF
allow_empty_password = false
animation = dur_file
# animation_frame_delay left at its own default (5ms): unlike the old
# Lua script, nothing here redraws the whole screen on every tick, so
# there's no CPU reason to slow it down, and each frame's own "delay"
# in sobarch-logo.dur (50ms during the reveal/disperse, 3s on the
# hold) is what actually paces the animation regardless.
dur_file_path = $LOGO_DUR
dur_offset_alignment = center
bigclock = none
clock = %a %d %b  %H:%M
bg = 0x00282c34
fg = 0x00abb2bf
border_fg = 0x0061afef
hide_borders = false
EOF

echo "ly-theme-setup.sh: done (unverified, check the greeter on first reboot)."
