-------------------------
---- TINTY / COLORS ----
-------------------------

-- Generated by tinty's base16-hyprland-lua item (~/.config/tinty/config.toml);
-- ships as a static base16-onedark default in skel so this is always
-- present regardless of whether tinty-git has actually built/installed
-- yet.
local colors = require("colors")

-- Hyprland's own color fields need "rgba(RRGGBBAA)"/"rgb(RRGGBB)" (hex
-- digits in parens, no `#`), but colors.lua's values are plain
-- '#RRGGBB' strings -- confirmed directly against Hyprland's own Lua
-- color-field parser, which only accepts the parens form.
local function rgb(hex)
	return "rgb(" .. hex:sub(2) .. ")"
end
local function rgba(hex, alpha)
	return "rgba(" .. hex:sub(2) .. alpha .. ")"
end

------------------
---- MONITORS ----
------------------

-- Generic fallback: matches any monitor not covered by a machine-specific rule below.
hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})

-- Machine-specific monitor layout and workspace pinning. Not tracked by the dotfiles/distro defaults; safe to be absent.
pcall(dofile, os.getenv("HOME") .. "/.config/hypr/local.lua")

-- NVIDIA-specific env vars, deployed only on machines where hardware
-- detection found an NVIDIA GPU (see installer/archinstall/nvidia.lua).
-- Safe to be absent on AMD/Intel-only systems.
pcall(dofile, os.getenv("HOME") .. "/.config/hypr/nvidia.lua")

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("waybar & mako & hypridle & hyprpaper & udiskie")
	hl.exec_cmd("fcitx5")
	hl.exec_cmd("xdg-user-dirs-update")
	-- `tinty-git` is base-required (always installed), but `command -v`
	-- guards anyway: an already-installed system only picks up a newly
	-- base-required package once its "Update Config" flow runs, and a
	-- package build can always fail. `tinty list` is empty until `tinty
	-- install` has cloned/built the scheme and template repos declared
	-- in config.toml; nothing else in sobarch ever runs that, so it's
	-- done here, once, self-healing on every login rather than gated
	-- behind a marker file: cheap to re-check (`tinty list` is local, no
	-- network) and correct even if a prior attempt was interrupted (e.g.
	-- no network yet at login).
	-- `tinty init` (re-applies the last-applied or default scheme)
	-- still runs every login same as before.
	hl.exec_cmd("command -v tinty >/dev/null 2>&1 && { tinty list | grep -q . || tinty install; tinty init; }")
end)

hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"')
hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
hl.exec_cmd('gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"')

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 5,

		border_size = 2,

		col = {
			active_border = { colors = { rgba(colors.base0D, "ee"), rgba(colors.base0C, "ee") }, angle = 45 },
			inactive_border = rgba(colors.base01, "aa"),
		},

		resize_on_border = false,
		allow_tearing = false,
		layout = "dwindle",
	},

	decoration = {
		rounding = 10,
		rounding_power = 2,

		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = false,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},

		blur = {
			enabled = false,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = false,
	},
})

hl.config({
	dwindle = {
		preserve_split = true,
	},
})

hl.config({
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		follow_mouse = 1,

		sensitivity = 0,
		accel_profile = "flat",

		touchpad = {
			natural_scroll = true,
		},
	},
})

---------------------
---- KEYBINDINGS ----
---------------------

require("keybinds")

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({
	name = "suppress-maximize-events",
	match = { class = ".*" },
	suppress_event = "maximize",
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

hl.window_rule({
	name = "float-network-manager",
	match = { title = ".*Network Manager.*" },
	float = true,
})

hl.layer_rule({
	name = "no-anim-fuzzel",
	match = { namespace = "^(fuzzel)$" },
	no_anim = true,
})
