#!/usr/bin/env bash
# Installs an optional package profile after first boot: for a profile
# skipped at install time, or one wanted later. Official packages
# install directly via pacman; AUR/custom packages go through
# aur-sync.sh's explicit-package mode -- the same combined logic
# install-profile-packages.sh already runs at first boot for whatever
# was selected during install, re-exposed here as a user-triggered
# action for anything not selected then.
#
# Reads /usr/share/sobarch/profiles.txt, a plain-text mirror of
# installer/tui/profiles_data.py's PROFILES (regenerated by hand via
# installer/tui/generate_profile_data.py whenever PROFILES changes;
# there is no Python on an installed system to read profiles_data.py
# directly). One line per profile: slug|Display Name|pkg1,pkg2:aur,...
# (a trailing :aur marks a packages/aur/ or packages/custom/ package).

set -euo pipefail

DATA_FILE="/usr/share/sobarch/profiles.txt"
AUR_SYNC="/usr/local/lib/sobarch/aur-sync.sh"

if [[ ! -r "$DATA_FILE" ]]; then
    notify-send -u critical "sobarch: install profile" "$DATA_FILE not found; is sobarch-skel installed?"
    exit 1
fi

declare -A profile_packages
labels=()
while IFS='|' read -r slug name pkgs; do
    [[ -n "$slug" ]] || continue
    label="󰏖  $name"
    labels+=("$label")
    profile_packages["$label"]="$pkgs"
done < "$DATA_FILE"

choice=$(printf '%s\n' "${labels[@]}" | fuzzel --dmenu --prompt "install profile: ")
[[ -n "${choice:-}" && -n "${profile_packages[$choice]:-}" ]] || exit 0
name="${choice#*  }"

IFS=',' read -ra pkgs <<< "${profile_packages[$choice]}"
official=()
aur=()
for pkg in "${pkgs[@]}"; do
    if [[ "$pkg" == *:aur ]]; then
        aur+=("${pkg%:aur}")
    else
        official+=("$pkg")
    fi
done

notify-send "sobarch: install profile" "Installing $name ($(( ${#official[@]} + ${#aur[@]} )) package(s))..."

fail=0
if ((${#official[@]})); then
    pkexec pacman -S --needed --noconfirm "${official[@]}" || fail=1
fi
if ((${#aur[@]})); then
    pkexec "$AUR_SYNC" "${aur[@]}" || fail=1
fi

if ((fail)); then
    notify-send -u critical "sobarch: install profile" \
        "$name: one or more packages failed; check /var/log/sobarch/aur-sync.log and pacman's own log."
else
    notify-send "sobarch: install profile" "$name installed."
fi
