format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration
$character"""

right_format = ""
add_newline = true

[fill]
symbol = " "

[directory]
style = "bold fg:#88c0d0"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "fg:#8fbcbb"
symbol = " "

[git_status]
style = "fg:#bf616a"

[cmd_duration]
min_time = 2000
style = "fg:#ebcb8b"

[character]
success_symbol = "[❯](bold fg:#a3be8c)"
error_symbol = "[❯](bold fg:#bf616a)"
