"""Regenerates the package-list table in
content/docs/installer/software-profiles.md from
packages/custom/sobarch-skel/data/profiles.txt.

Deliberately reads that plain pipe-delimited file, not
installer/tui/profiles_data.py directly: profiles.txt is already the
language-agnostic contract setup-profile-menu.sh (plain bash, no
Python assumed) depends on, so this script rides along on the same
contract instead of parsing installer internals. If the installer is
ever rewritten in something other than Python, this keeps working
unchanged as long as whatever replaces it still emits profiles.txt in
this format, which it has to anyway for that bash script's sake.

Not run automatically by anything, same as
installer/tui/generate_profile_data.py: re-run that script first if
PROFILES changed, then re-run this one by hand.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PROFILES_TXT = REPO_ROOT / "packages/custom/sobarch-skel/data/profiles.txt"
DOC_PAGE = REPO_ROOT / "website/content/docs/installer/software-profiles.md"

START = "<!-- profiles:start (auto-generated by website/scripts/generate-profiles-doc.py, do not edit by hand) -->"
END = "<!-- profiles:end -->"


def render_table() -> str:
    lines = ["| Profile | Packages |", "| --- | --- |"]
    for line in PROFILES_TXT.read_text().splitlines():
        if not line.strip():
            continue
        _slug, name, pkgs_field = line.split("|", 2)
        pkgs = []
        for pkg in pkgs_field.split(","):
            if pkg.endswith(":aur"):
                pkgs.append(f"`{pkg[:-4]}` (AUR)")
            else:
                pkgs.append(f"`{pkg}`")
        lines.append(f"| **{name}** | {', '.join(pkgs)} |")
    return "\n".join(lines)


def main() -> None:
    doc = DOC_PAGE.read_text()
    if START not in doc or END not in doc:
        raise SystemExit(f"markers not found in {DOC_PAGE}")
    before, rest = doc.split(START, 1)
    _, after = rest.split(END, 1)
    DOC_PAGE.write_text(f"{before}{START}\n{render_table()}\n{END}{after}")
    print(f"wrote {DOC_PAGE}")


if __name__ == "__main__":
    main()
