# Base16 OneDark
# Author: Lalit Magant (http://github.com/tilal6991)

[colors]
background=282c34ff
text=abb2bfff
prompt=61afefff
placeholder=545862ff
input=abb2bfff
match=61afefff
selection=3e445133
selection-text=b6bdcaff
selection-match=61afefff
border=61afefff
