#!/usr/bin/env bash
# First-boot half of the rescue media setup. installer/archinstall/
# rescue-iso-setup.sh only formats and labels RESCUE/RESCUEBOOT at
# install time and drops /etc/sobarch/rescue-pending; this fills them
# once the network is up, so the ~1.3GB ISO download never blocks the
# install itself.
#
# The fetch/write is refresh-rescue-iso.sh as-is (it finds the media by
# label, which is exactly what the install-time script set up). The
# Limine entry is the only thing refresh never does, so it's added
# here, after the files exist: an entry pointing at a kernel that was
# never written would just be a broken boot menu item.
#
# A failure leaves rescue-pending in place, so the next network "up"
# retries from scratch.

set -euo pipefail

[ -e /etc/sobarch/rescue-pending ] || exit 0

/usr/local/lib/sobarch/refresh-rescue-iso.sh

RESCUE_DEV="$(blkid -L RESCUE)"
RESCUE_UUID=$(blkid -s UUID -o value "$RESCUE_DEV")

if [ -d /sys/firmware/efi ]; then
    # Limine's guid()/uuid() path resolver matches a filesystem UUID or
    # a GPT partition GUID, both full 128-bit values -- never FAT32's
    # own "UUID" (blkid -s UUID), which is really just its short 32-bit
    # volume serial number and never matches. The partition's own GPT
    # PARTUUID is the one identifier FAT32 actually has that fits.
    RESCUE_BOOT_PARTUUID=$(blkid -s PARTUUID -o value "$(blkid -L RESCUEBOOT)")
    KERNEL_PATH="uuid(${RESCUE_BOOT_PARTUUID}):/vmlinuz-linux"
    INITRD_PATH="uuid(${RESCUE_BOOT_PARTUUID}):/initramfs-linux.img"
    LIMINE_CONF="/boot/EFI/BOOT/limine.conf"
else
    KERNEL_PATH="boot():/rescue/vmlinuz-linux"
    INITRD_PATH="boot():/rescue/initramfs-linux.img"
    LIMINE_CONF="/boot/limine/limine.conf"
fi

START_MARKER="#### SOBARCH RESCUE ENTRY START (auto-generated by setup-rescue-iso.sh, do not edit by hand)"
END_MARKER="#### SOBARCH RESCUE ENTRY END"

# Own delimited block, distinct from sobarch-limine-snapshot-sync's own
# "SOBARCH SNAPSHOTS" block, so the two never clobber each other or
# archinstall's own base OS entry when either regenerates.
block="$START_MARKER
/Arch Linux rescue (local ISO)
    protocol: linux
    path: ${KERNEL_PATH}
    module_path: ${INITRD_PATH}
    cmdline: archisobasedir=arch img_dev=UUID=${RESCUE_UUID} img_loop=/archlinux-x86_64.iso
$END_MARKER"

if grep -qF "$START_MARKER" "$LIMINE_CONF"; then
    awk -v start="$START_MARKER" -v end="$END_MARKER" -v block="$block" '
        $0 == start { print block; skipping = 1; next }
        $0 == end && skipping { skipping = 0; next }
        skipping { next }
        { print }
    ' "$LIMINE_CONF" > "${LIMINE_CONF}.sobarch-new"
    mv "${LIMINE_CONF}.sobarch-new" "$LIMINE_CONF"
else
    printf '\n%s\n' "$block" >> "$LIMINE_CONF"
fi

rm -f /etc/sobarch/rescue-pending
echo "setup-rescue-iso: done."
